### PR TITLE
Remove duplication for image paramterization

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Review by kosack — APPROVED** [review]

**Comment by kosack** [comment]
should I fix the merge conflicts (sorry was due to an earlier commit from me)?

**Comment by maxnoe** [comment]
I'm on it

**Comment by maxnoe** [comment]
Wait, when I pulled from your branch, the merge conflicts were gone...

What happend?

**Comment by kosack** [comment]
> Wait, when I pulled from your branch, the merge conflicts were gone...

they weren't really conflicts, I think it was just that I pushed a small commit in between so it resolved itself when you pulled

**Comment by kosack** [comment]
> /home/travis/build/kosack/ctapipe/ctapipe/image/morphology.py:docstring of ctapipe.image.morphology_parameters:6:Unexpected indentation.

It's mentioning unexpected indentation in the docs, but I don't see a problem

**Pull request merged**
