### PR TITLE
Store pointing info in dl1 tool

### PR DESCRIPTION
**Pull request by maxnoe**
Here I store unique pointings (don't know if that's really a good idea) to

`/monitoring/subarray/pointing` and `/monitoring/telescope/pointing`

### CODE REVIEW

**Comment by maxnoe** [comment]
@kosack seems the travis error was a network hickup, can you restart the two builds that failed?

**Review by kosack — APPROVED** [review]

**Comment by kosack** [comment]
> @kosack seems the travis error was a network hickup, can you restart the two builds that failed?

rerunning

**Comment by kosack** [comment]
Currently there is no `/monitoring` data: so the question is is whether this is really `/dl0/monitoring/pointing` or `/dl1/monitoring/pointing`.  There would be some transformation/processing between the two. I think here it's really  `/dl1/monitoring/pointing`, and eventually we would also add columns for the pointing transforms in that table, not just the corrected position (rotation, and skew and maybe focal length if needed).  These would be computed elsewhere from the DL0 pointing data + the pointing correction system data.  for MCs, so far that is not needed, but it will be eventually.

**Review by kosack — CHANGES_REQUESTED** [review]
So I'd recommend for now renaming it to `/dl1/monitoring/..`

Basically, DL1 pointing  is the  DL0 pointing with any calibration/corrections either applied or supplied along with it

**Comment by maxnoe** [comment]
Interesting. I thought service / monitoring data would live independent of the *data* levels tree. This seems completely independent of data processing to me. 

But if that's the way it is for now, I will change it

**Comment by maxnoe** [comment]
done

**Comment by maxnoe** [comment]
@kosack I implemented the requested changes

**Comment by kosack** [comment]
I think the pointing monitoring containers should have a time stamp (as they would have in reality), not an event_id. So then the interpolation is by time, not by event id (which can be non-uniform)

Right now, you have:

image

But it should be just `time, azimuth, altitude`.  Also, I'd guess we should have one pointing table per telescope as with other tables, rather than a single one with a tel_id index (though either would work in practice, real data would be taken by each  telescope independently)

**Comment by kosack** [comment]
While we are at it, should be add the mispointing parameters here? That would help support real data.  So the table would be at least:

`time, azimuth, altitude, delta_x, delta_y, rotation` (plus any other parameters needed -  I'd have to asl the hardware people if there are other corrections like skews or rotations other than around the camera normal, etc)

or wa ssume the alt/az position is already corrected, in which case you only need the rotation and not delta_x/y. 

That way this is clearly DL1 data: it's the DL0 pointing with corrections applied (or recorded)

**Comment by maxnoe** [comment]
I replaced the event index with the trigger time. I think we should postpone the discussion about the pointing corrections to later.

Concerning your discussions of pointing data levels, I would assume that dl1 pointing data should already be corrected

**Comment by kosack** [comment]
> Concerning your discussions of pointing data levels, I would assume that dl1 pointing data should already be corrected

agreed, so then it would only need other corrections to be along with it, specifically the rotation (which must be applied during analysis).

**Comment by kosack** [comment]
ok looks good

**Pull request merged**
